require '2_euler'
require 'rspec'

	# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	# By starting with 1 and 2, the first 10 terms will be:
	# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	# find the sum of the even-valued terms.

describe "#euler_2" do
  it "returns correct answer for simple example" do
    euler_2(10).should == 10
  end

  it "returns 0 for 0" do
    euler_2(0).should == 0
  end

  it "works for less simple example" do
    euler_2(45).should == 44
  end

end
