	# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	# By starting with 1 and 2, the first 10 terms will be:
	# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	# find the sum of the even-valued terms.

def euler_2(int)
  sum = 0
  fib_array = [1, 2]
  while fib_array.last < int
	fib_array << (fib_array[-2] + fib_array[-1])
  end
  fib_array.pop
  fib_array.each do |x|
  	if x % 2 == 0
  	  sum += x
    end
  end
  if int == 0
  	return 0
  end
  sum
end

puts euler_2(4000000)